module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.mock.ts'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/__tests__/',
    '/migrations/',
    '/config/',
  ],
  collectCoverageFrom: [
    'src/services/loanService.ts',
    'src/services/fundingService.ts',
    'src/services/transferService.ts',
    'src/services/userService.ts',
    'src/services/walletService.ts',
    'src/controllers/userController.ts',
    'src/controllers/walletController.ts',
    'src/middleware/errorHandler.ts',
    'src/repositories/userRepository.ts',
    'src/repositories/walletRepository.ts',
    'src/repositories/transactionRepository.ts',
    'src/utils/logger.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 80,
      statements: 80,
    },
  },
  testTimeout: 30000,
};
